[package]
publish = false
name = "placeholder"
version = "0.0.0"

[dev-dependencies]
dotenv-linter = "3.3.0"
hush = "0.1.4"
shellharden = "4.3.0"

[[bin]]
name = "placeholder"
path = "placeholder.rs"

# [profile.release]
# strip = "debuginfo"
# lto = true
