version: 2

updates:
  # CI
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Main
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "00:30"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Dependencies
  - package-ecosystem: npm
    directory: /dependencies
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: composer
    directory: /dependencies
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:30"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: /dependencies
    schedule:
      interval: daily
      time: "02:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: bundler
    directory: /dependencies
    schedule:
      interval: daily
      time: "02:30"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: cargo
    directory: /dependencies
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Docs
  - package-ecosystem: npm
    directory: /doc/record
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: /doc/record
    schedule:
      interval: daily
      time: "03:30"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
