version: 2

shared-settings: &shared-settings
  schedule:
    interval: daily
    time: "13:00"
    timezone: "Europe/Bratislava"
  open-pull-requests-limit: 10
  reviewers:
    - matejkosiarcik
  assignees:
    - matejkosiarcik

updates:
  # Runner
  - package-ecosystem: npm
    directory: "/runner"
    versioning-strategy: increase
    <<: *shared-settings
  - package-ecosystem: docker
    directory: "/runner"
    <<: *shared-settings

  # Alpine
  - package-ecosystem: docker
    directory: "/components/alpine"
    <<: *shared-settings

  # Brew
  - package-ecosystem: docker
    directory: "/components/brew"
    <<: *shared-settings

  # Composer
  - package-ecosystem: docker
    directory: "/components/composer"
    <<: *shared-settings
  - package-ecosystem: composer
    directory: "/components/composer"
    versioning-strategy: increase
    <<: *shared-settings

  # Debian
  - package-ecosystem: docker
    directory: "/components/debian"
    <<: *shared-settings

  # Go
  - package-ecosystem: docker
    directory: "/components/go"
    <<: *shared-settings

  # Node
  - package-ecosystem: docker
    directory: "/components/node"
    <<: *shared-settings
  - package-ecosystem: npm
    directory: "/components/node"
    versioning-strategy: increase
    <<: *shared-settings

  # Python
  - package-ecosystem: docker
    directory: "/components/python"
    <<: *shared-settings
  - package-ecosystem: pip
    directory: "/components/python"
    <<: *shared-settings

  # Shellcheck
  - package-ecosystem: docker
    directory: "/components/shellcheck"
    <<: *shared-settings
