version: 2

updates:
  # Main Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Main CLI
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # CI
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Linters
  - package-ecosystem: npm
    directory: /linters
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: composer
    directory: /linters
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: /linters
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: bundler
    directory: /linters
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: cargo
    directory: /linters
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Build dependencies
  - package-ecosystem: npm
    directory: /build-dependencies/yaml-minifier
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: /build-dependencies/gitman
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: /build-dependencies/yq
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1

  # Docs
  - package-ecosystem: npm
    directory: /doc/record
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: /doc/record
    schedule:
      interval: daily
      time: "01:00"
      timezone: Europe/Bratislava
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
