version: 2

updates:
  - package-ecosystem: npm
    directory: "/runner"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
