version: 2

updates:
  # Runner
  - package-ecosystem: npm
    directory: "/runner"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
  - package-ecosystem: docker
    directory: "/runner"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Alpine
  - package-ecosystem: docker
    directory: "/components/alpine"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Bash
  - package-ecosystem: docker
    directory: "/components/bash"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Brew
  - package-ecosystem: docker
    directory: "/components/brew"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Composer
  - package-ecosystem: docker
    directory: "/components/composer"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
  - package-ecosystem: composer
    directory: "/components/composer"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Debian
  - package-ecosystem: docker
    directory: "/components/debian"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Go
  - package-ecosystem: docker
    directory: "/components/go"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Haskell
  - package-ecosystem: docker
    directory: "/components/haskell"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Node
  - package-ecosystem: docker
    directory: "/components/node"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
  - package-ecosystem: npm
    directory: "/components/node"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Python
  - package-ecosystem: docker
    directory: "/components/python"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
  - package-ecosystem: pip
    directory: "/components/python"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Swift
  - package-ecosystem: docker
    directory: "/components/swift"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  # Zsh
  - package-ecosystem: docker
    directory: "/components/zsh"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
