version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  # Main runner
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  # Components/dependencies
  - package-ecosystem: npm
    directory: "/dependencies"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
  - package-ecosystem: composer
    directory: "/dependencies"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
  - package-ecosystem: pip
    directory: "/dependencies"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
  - package-ecosystem: bundler
    directory: "/dependencies"
    schedule:
      interval: daily
      time: "02:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
