language: minimal

services:
  - docker

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

jobs:
  include:
    - { os: linux, dist: focal }
    - { os: linux, dist: bionic }
    - { os: linux, dist: xenial }

install:
  - nvm install node  # otherwise node is not available
  - make bootstrap

script:
  - make build
  - make run
