language: minimal

os:
  - osx
  - linux

addons:
  apt:
    update: true
  homebrew:
    update: true

jobs:
  include:
    - { if: branch = master, os: linux, dist: bionic }
    - { if: branch = master, os: linux, dist: xenial }

    - os: linux
      services: docker
      install:
        - docker build --tag azlint:dev .
      script:
        - docker run --interactive --tty --rm --volume "${PWD}:/mount" azlint:dev

before_install:
  - uname -a
  - if [ "$(uname -s)" = 'Darwin' ]; then sw_vers; fi

install:
  - |
    if command -v apt-get >/dev/null 2>&1; then
      nvm install node # otherwise node is not available
      eval "$(gimme stable)" # otherwise go-v1.11 is present
    fi
  - |
    if [ "$(uname -s)" = Darwin ] && brew list python2 >/dev/null 2>&1; then
      brew unlink python2;
    fi
  - sh 'utils/install.sh'

script:
  - sh 'utils/lint.sh'
