language: minimal

services:
  - docker

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

jobs:
  fast_finish: true
  allow_failures:
    - arch: arm64
    - arch: ppc64le
    - arch: s390x
  include:
    - { os: linux, dist: focal, arch: amd64 }

install:
  - nvm install node # otherwise node is not available
  - make bootstrap

script:
  - make build
  - make run
