[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 150
disable = [
  "fixme",
  "wildcard-import",
  "unused-wildcard-import",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring"
]
