exclude = [
  '^https://bevry\.me', # Frequent timeouts
  '^https://(?:www\.)?patreon\.com/feross', # 403s
  '^https://(?:www\.)?shellcheck\.net', # HTTPS errors
  '^https://gitlab\.gnome\.org/GNOME/libxml2', # 503
  '^http://www\.xmlsoft\.org', # Timeouts + 504
  '^https://(?:www\.)?gnu\.org', # Timeouts
  '^shivammathur/setup-php@.+$', # Invalid email address
  '^https?://localhost',
  '^https?://.*\.lan',
]
