exclude = [
  '^https://bevry\.me', # Frequent timeouts
  '^https://(?:www.)?patreon\.com/feross', # 403s
  '^https://(?:www.)?shellcheck\.net', # HTTPS errors
  '^shivammathur/setup-php@.+$', # Invalid email address
  '^https?://localhost',
  '^https?://.*\.lan',
]
