[tool.isort]
profile = "black"

[tool.black]
line-length = 300

[tool.pyink]
line-length = 300

[tool.pylint.messages_control]
max-line-length = 300
disable = [
  "duplicate-code",
  "fixme",
  "invalid-name",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "no-else-return",
  "too-few-public-methods",
  "unused-wildcard-import",
  "wildcard-import"
]
