diff --git a/Makefile b/Makefile
index afaf28f..f953436 100644
--- a/Makefile
+++ b/Makefile
@@ -25,7 +25,7 @@ clean: ## Clean bin/ directory
 	rm -f ./bin/*

 define _build
-go build -ldflags "-X main.version=$(CURRENT_VERSION)" -o $1 ./cmd/editorconfig-checker/main.go
+go build -ldflags "-s -w -buildid=" -o $1 ./cmd/editorconfig-checker/main.go
 endef

 $(EXE): $(SOURCES) VERSION
