name: Build

permissions: read-all

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
  DOCKER_IMAGE: matejkosiarcik/azlint

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    name: Build - ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup QEMU
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: docker/setup-qemu-action@v4.4.0
          attempt_limit: 3
          attempt_delay: 2500

      - name: Setup Docker Buildx
        id: buildx
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: docker/setup-buildx-action@v4.4.1
          attempt_limit: 3
          attempt_delay: 2500

      - name: Build
        uses: docker/build-push-action@v7.4.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          platforms: "${{ matrix.platform }}"
          push: false
          tags: "${{ env.DOCKER_IMAGE }}:dev"

      - name: AZLint lint
        if: ${{ matrix.platform == 'linux/amd64' }}
        run: |
          docker run --interactive --rm \
            --volume "$PWD:/project:ro" \
            --platform ${{ matrix.platform }} \
            matejkosiarcik/azlint:dev lint

      - name: Check git status - before formatting
        if: ${{ matrix.platform == 'linux/amd64' }}
        run: |
          if [ "$(git status --short | wc -l)" -ne 0 ]; then
            printf 'Found following changes before formatting:\n'
            git status
            exit 1
          fi

      - name: AZLint fmt
        if: ${{ matrix.platform == 'linux/amd64' }}
        run: |
          docker run --interactive --rm \
            --volume "$PWD:/project" \
            --platform ${{ matrix.platform }} \
            matejkosiarcik/azlint:dev fmt

      - name: Check git status - after formatting
        if: ${{ matrix.platform == 'linux/amd64' }}
        run: |
          if [ "$(git status --short | wc -l)" -ne 0 ]; then
            printf 'Found following changes after formatting:\n'
            git status
            exit 1
          fi
