name: Build2

permissions: read-all

on:
  pull_request:

jobs:
  build2:
    name: Build2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Setup Cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build
        uses: docker/build-push-action@v4.1.1
        with:
          platforms: linux/amd64
          push: false
          tags: matejkosiarcik/azlint:dev
