name: Deploy dockerhub description

permissions: read-all

on:
  push:
    branches:
      - main
      - develop

jobs:
  predeploy:
    name: PreDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Echo
        run: echo 'Predeploy...'

  deploy:
    name: Deploy
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: matejkosiarcik/azlint
          short-description: ${{ github.event.repository.description }}
