name: Deploy to DockerHub

permissions: read-all

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"

env:
  REGISTRY_IMAGE: matejkosiarcik/azlint

jobs:
  build-images:
    name: Build image - ${{ matrix.platform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      # - name: Docker tags
      #   uses: docker/metadata-action@v4.6.0
      #   id: meta
      #   with:
      #     images: matejkosiarcik/azlint
      #     # NOTE: `:latest` tag is added automatically on `type=semver`
      #     tags: |
      #       type=edge,branch=main
      #       type=semver,pattern={{major}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.9.1

      # - name: Debug logs
      #   run: |
      #     printf "Available platforms:\n%s\n" "${{ steps.buildx.outputs.platforms }}"
      #     printf "Building tags:\n%s\n" "${{ steps.meta.outputs.tags }}"

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish
        id: build
        uses: docker/build-push-action@v4.1.1
        with:
          platforms: ${{ matrix.platform }}
          # push: true
          # tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v3.1.2
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  deploy-description:
    name: Update description
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: matejkosiarcik/azlint
          short-description: ${{ github.event.repository.description }}
